<?php
    $userData = array(
        "https://bootdey.com/img/Content/avatar/avatar1.png", 1, "Saif Alnuaimi Alnuaimi", "Founder & CEO","07-05-1976",
         "Web Developer", "Facebook", "saifalnuaimi@mail.com", "I am a Front End developer with industry experience building websites and web applications. I specialize in HTML, CSS, SCSS, Bootstrap and jQuery. I am passionate, resourceful and always love to learn new things. I love shaping new ideas into meaningful chunks.", "Many people take no care of their money till they come nearly to the end of it, and others do just the same with their time.", 85, 90, 80, "It is truly amazing the damage that we, as parents, can inflict on our children. So why do we do it? For the most part, we don’t do it intentionally or with malice. In the majority of cases, the cause is a well-meaning but unskilled or un-thinking parent, who says the wrong thing at the wrong time, and the message sticks – as simple as that!",
         "https://bootdey.com/img/Content/avatar/avatar1.png", 1, "Nazrul Islam", "UI Designer","01-02-1985",
         "Web Developer", "Facebook", "saifalnuaimi@mail.com", "I am a Front End developer with industry experience building websites and web applications. I specialize in HTML, CSS, SCSS, Bootstrap and jQuery. I am passionate, resourceful and always love to learn new things. I love shaping new ideas into meaningful chunks.", "Many people take no care of their money till they come nearly to the end of it, and others do just the same with their time.", 85, 90, 80, "It is truly amazing the damage that we, as parents, can inflict on our children. So why do we do it? For the most part, we don’t do it intentionally or with malice. In the majority of cases, the cause is a well-meaning but unskilled or un-thinking parent, who says the wrong thing at the wrong time, and the message sticks – as simple as that!",
        "https://bootdey.com/img/Content/avatar/avatar6.png", 3, "Riyadh Khan", "Developer","26-09-1979",
        'Engineer', 'NASA', "Riyadh.Khan@mail.com", "I’m a web developer. I spend my whole day, practically every day, experimenting with HTML, CSS, and JavaScript; dabbling with Python and Ruby; and inhaling a wide variety of potentially useless information through a few hundred RSS feeds. I build websites that delight and inform. I do it well.", "A software development quotation is a project cost estimate, usually sent with a software development proposal before you start the job.", 90, 95, 100, "In the USA, there are more Chinese restaurants than all the McDonald’s, KFCs, Burger Kings and Wendy’s put together.",
        "https://bootdey.com/img/Content/avatar/avatar2.png", 4, "Niloy Islam", "Marketing Manager","17-12-1977",
         "CEO", "Facebook", "Niloy.Islam@mail.com", "I’m a software engineer in Santa Barbara, CA with a passion for computer science, electrical engineering and embedded systems technology.", "Wealth consists not in having great possessions, but in having few wants", 75, 95, 85, "Though less common than earthquakes, the moon actually has moonquakes, too. That's right. Moonquakes. Pretty much everyone is interested in space, so this is always a good fact to pull out."
    );
    
    
?>